### PR TITLE
Migrate tests

### LINKED ISSUE #265: Move automated tests from Travis CI to GitHub Actions
Per the decision in a previous engineering meeting.

### PR DESCRIPTION
**Pull request by AyanChoudhary**
Fixes #265 

This PR migrates the CI tests from Travis to Github actions.
---

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by AyanChoudhary** [comment]
I have migrated all the steps but I can't seem to get the Postgres container running. Can someone help me in this regard? @brenoferreira @kgodey

**Comment by kgodey** [comment]
@aldenstpage

**Comment by AyanChoudhary** [comment]
In this case, the postgres is being used as a service for the github workflow. But when the workflow is executed it reports that the postgres service does not exist. For the testing part there is a cli-tool [act](https://github.com/nektos/act) but it does not support the python in its native environment. To test python we will need one of the docker images it provides, but the image is quite large which makes testing take a very large time. Alternatively, we can just test the workflow from the actions log log it generates in the actions panel.

**Comment by AyanChoudhary** [comment]
> In this case, the postgres is being used as a service for the github workflow. But when the workflow is executed it reports that the postgres service does not exist. For the testing part there is a cli-tool [act](https://github.com/nektos/act) but it does not support the python in its native environment. To test python we will need one of the docker images it provides, but the image is quite large which makes testing take a very large time. Alternatively, we can just test the workflow from the actions log log it generates in the actions panel.

@aldenstpage

**Comment by AyanChoudhary** [comment]
@aldenstpage I have fixed the postgres issue and have also tested the script, there is just a small issue with the tests which make request to API_URL(of which I am attaching screenshots below)
Screenshot from 2020-03-16 23-32-03

**Comment by aldenstpage** [comment]
What do the server logs say? An error 500 suggests that there's a configuration issue.

**Comment by AyanChoudhary** [comment]
@aldenstpage sending the error log below, I guess this is some kind of authorization error. It would be great if you could confirm this.

```
DELETE http://es:9200/image/_doc/719 [status:403 request:0.003s]
web_1_24d68fb14294  | Internal Server Error: /v1/images/d52cacae-eecb-429c-83be-29c4e3095339
web_1_24d68fb14294  | Traceback (most recent call last):
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1_24d68fb14294  |     response = get_response(request)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1_24d68fb14294  |     response = self.process_exception_by_middleware(e, request)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1_24d68fb14294  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_1_24d68fb14294  |     return view_func(*args, **kwargs)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
web_1_24d68fb14294  |     return self.dispatch(request, *args, **kwargs)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
web_1_24d68fb14294  |     response = self.handle_exception(exc)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
web_1_24d68fb14294  |     self.raise_uncaught_exception(exc)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
web_1_24d68fb14294  |     raise exc
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
web_1_24d68fb14294  |     response = handler(request, *args, **kwargs)
web_1_24d68fb14294  |   File "/cccatalog-api/cccatalog/api/views/image_views.py", line 172, in delete
web_1_24d68fb14294  |     es.delete(index='image', id=image.id)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
web_1_24d68fb14294  |     return func(*args, params=params, **kwargs)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 579, in delete
web_1_24d68fb14294  |     "DELETE", _make_path(index, doc_type, id), params=params
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
web_1_24d68fb14294  |     timeout=timeout,
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_requests.py", line 163, in perform_request
web_1_24d68fb14294  |     self._raise_error(response.status_code, raw_data)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
web_1_24d68fb14294  |     status_code, error_message, additional_info
web_1_24d68fb14294  | elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, 'cluster_block_exception', 'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
web_1_24d68fb14294  | Internal Server Error: /v1/images/d52cacae-eecb-429c-83be-29c4e3095339
web_1_24d68fb14294  | Traceback (most recent call last):
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1_24d68fb14294  |     response = get_response(request)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1_24d68fb14294  |     response = self.process_exception_by_middleware(e, request)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1_24d68fb14294  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_1_24d68fb14294  |     return view_func(*args, **kwargs)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
web_1_24d68fb14294  |     return self.dispatch(request, *args, **kwargs)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
web_1_24d68fb14294  |     response = self.handle_exception(exc)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
web_1_24d68fb14294  |     self.raise_uncaught_exception(exc)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
web_1_24d68fb14294  |     raise exc
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
web_1_24d68fb14294  |     response = handler(request, *args, **kwargs)
web_1_24d68fb14294  |   File "/cccatalog-api/cccatalog/api/views/image_views.py", line 172, in delete
web_1_24d68fb14294  |     es.delete(index='image', id=image.id)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
web_1_24d68fb14294  |     return func(*args, params=params, **kwargs)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 579, in delete
web_1_24d68fb14294  |     "DELETE", _make_path(index, doc_type, id), params=params
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
web_1_24d68fb14294  |     timeout=timeout,
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_requests.py", line 163, in perform_request
web_1_24d68fb14294  |     self._raise_error(response.status_code, raw_data)
web_1_24d68fb14294  |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
web_1_24d68fb14294  |     status_code, error_message, additional_info
web_1_24d68fb14294  | elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, 'cluster_block_exception', 'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
```

**Comment by aldenstpage** [comment]
I haven't seen this error before either. I did a Google search and found [this](https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282) and [this](https://stackoverflow.com/questions/48155774/elasticsearch-read-only-allow-delete-auto-setting); perhaps the disk space GitHub actions provides for us isn't sufficiently large to hold the docker containers (likely) or our sample data CSV (less likely). That should be a good starting point for investigation for you.

**Comment by AyanChoudhary** [comment]
I don't think the size of the VM is the issue here because the default specs are:
Each virtual machine has the same hardware resources available.

2-core CPU
7 GB of RAM memory
14 GB of SSD disk space

And the size of the containers is only 4.059GB and the csv is 12MB. So I don't think memory is the issue. I will look for the ```read only index block``` though to see if that is the issue.

**Comment by AyanChoudhary** [comment]
Another update on this issue. I am running into the same error when I run the tests on my environment as well. So it definitely not a space issue, but it is strange why I am facing the error on my local setup.

**Comment by aldenstpage** [comment]
Closing this after 30 days of inactivity; feel free to reopen it if you continue

**Pull request closed without merging**
