### PR TITLE
[WIP] Implement oEmbed endpoint

### LINKED ISSUE #445: Implement oEmbed endpoint
https://ombed.com
>oEmbed is a format for allowing an embedded representation of a URL on third party sites. The simple API allows a website to display embedded content (such as photos or videos) when a user posts a link to that resource, without having to parse the resource directly.

To support oEmbed, we are going to need to implement an API endpoint at `/v1/oembed`, which will accept parameters `url` and `format`. Fully implement the specification **except for wildcards**. Right now, we only have photos, so only implement the `photo` type. We want to support both JSON and XML formats (this should be as simple as switching Django renderers). Most importantly, we want to add a `license_url` field to the response, which will link to the CC License for an embedded image.

oEmbed requires a `height` and `width` field for images. In some cases, we don't know the dimensions of an image. In those cases, the `oEmbed` endpoint should load the image server-side and measure the dimensions before returning the fully populated response.

The endpoint must be cleanly represented in our generated documentation. There should be some unit tests demonstrating that the endpoint works as expected.

Example request:
GET `https://api.creativecommons.engineering/v1/oembed/?format=json&url=https%3A//search.creativecommons.org/photos/f5af4a72-9ab2-4f5a-a0c5-090e7350c209`

Response:
```
{
  "version": "1.0",
  "type": "photo",
  "width": 1024,
  "height": 768,
  "title": "kittens 022",
  "author_name": "bytehead",
  "author_url": "https://www.flickr.com/photos/66884677@N00",
  "license_url": "https://creativecommons.org/licenses/by-sa/2.0/"
}
```

We would also like to use the `html` field (normally not required for `photo` types) to embed additional rich attribution information as we do in the CC Search front end (optional for contributors; we can add this ourselves).

### PR DESCRIPTION
**Pull request by AyanChoudhary**
Fixes #445 

This PR will implement the oEmbed endpoint for cccatalog-api and will also contain the tests and the required documentation.
---

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by AyanChoudhary** [comment]
@aldenstpage can you just review the view and the corresponding response. I will be writing the tests in the meanwhile.

**Comment by Tanuj22** [comment]
@AyanChoudhary I already have a PR( #454 ) open for this and making the changes requested by @aldenstpage

**Comment by AyanChoudhary** [comment]
@aldenstpage I need to djangorestframework-xml package to enable the xml rendering, so where am I supposed to add it? Should I make changes to the Pipfile?

**Comment by AyanChoudhary** [comment]
I am getting a ModuleNotFound error even though I have added the framework to Pipfile and also made the changes in settings.py. Attaching the error and commit the new files. @aldenstpage can you please help here?
Screenshot from 2020-03-29 13-14-10

**Comment by aldenstpage** [comment]
I'm not sure what the source of the error is either, I would have to take some time to debug and investigate. We've taken another PR addressing this issue, but I encourage you to take a look at another ticket (especially finishing porting the tests because that would have some major quality-of-life improvements for other devs!)

**Pull request closed without merging**
