### PR TITLE
Added /license endpoint

### LINKED ISSUE #368: Create a /license endpoint
The endpoint should list every possible valid Creative Commons license. Each license in the response should have:

- The license version number
- The license URL
- The jurisdiction
- The language code

```
GET /v1/licenses
```
```
[
    {
        "license_version": 4.0,
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "jurisdiction": "us", 
        "language_code": "en"
    },
    {
    . . .
    }
    . . .
]
```

While we model licenses in a simple way in `licenses.py`, this is not sufficient for accurately listing all possible licenses. There are ~700 versions of licenses. The best way to get this information is to parse the license RDF spec [here](https://creativecommons.org/licenses/index.rdf). It should be parsed when the server is started up and kept in memory. I don't expect this spec to change very often, so instead of fetching it remotely, we should just keep a copy of it in this git repository.

### PR DESCRIPTION
**Pull request by tushar912**
## Fixes

Fixes #368  by @aldenstpage 

## Description
Created /license endpoint in the api to list all licenses from rdf file

## Screenshots
Firefox_Screenshot_2020-09-26T10-37-00 287Z

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by aldenstpage — CHANGES_REQUESTED** [review]
Hi @tushar912 – from your screenshot, this looks very promising. But it appears to violate the repository style guidelines and break the tests.

**Comment by aldenstpage** [comment]
Take a look at the [build](https://github.com/creativecommons/cccatalog-api/runs/1169852206) and see what commands are failing. You can also run the tests locally and see which step is failing

**Comment by tushar912** [comment]
@aldenstpage I have made changes so now it passes style test. But i am unable to understand why it is failing main test .The build says that <code>Pipfile.lock </code> out of date . Can u help me resolve this?

**Comment by aldenstpage** [comment]
It looks like it's because you added `rdflib` as a dependency but didn't commit the changes made to Pipfile.lock. If you push that file, that particular issue should be solved. If not, try `pipenv lock` and recommit.

**Comment by tushar912** [comment]
@aldenstpage I commited <code>Pipfile.lock</code> but now it shows conflicts and the tests wont run.

**Comment by aldenstpage** [comment]
Try reverting your changes to [Pipfile ](url) and [Pipfile.lock](url) entirely, running `pipenv install rdflib` again, and then committing both files to this PR. That seems like the root of the problem with the tests.

As for the merge conflicts, the PR is just slightly out of date with the other changes in the project; you can use the "resolve conflicts" UI to bring it up to date. I would put that off until after the tests have been fixed.

**Comment by tushar912** [comment]
Now I think it is passing the part of test it was failing earlier .But i am not able to find out why the test is timing out now.

**Comment by kgodey** [comment]
This repo has entered [maintenance mode](https://opensource.creativecommons.org/blog/entries/2020-12-07-upcoming-changes-to-community/) so we will not be merging this PR.

**Pull request closed without merging**
