### PR TITLE
Change response parameters for `/images` API

### LINKED ISSUE #452: A small documentation error under image_search
## Describe the bug
The 400 Bad Request response for the `images/` endpoint has keys: `error_type`, `field` and 
`detail`. But in the documentation, it is mentioned that the keys are: `error`, `fields` and `detail`.

Compare and contrast the api response in https://api.creativecommons.engineering/v1/images?q=+ and the keys for 400 response type under https://api.creativecommons.engineering/v1/#operation/image_search

### PR DESCRIPTION
**Pull request by kelvindecosta**
Fixes #452

#### Refactor confusing variable names (to match type)

The issue describes an inconsistency between the `400` response parameters of the [`image_search` api](https://api.creativecommons.engineering/v1/images) and the [documentation for the same](https://api.creativecommons.engineering/v1/#operation/image_search).

| docs     | response     | Description of the parameter            |
| -------- | ------------ | --------------------------------------- |
| `error`  | `error_type` | A string describing the type of error   |
| `fields` | `field`      | The list of fields that cause the error |

In this [comment](https://github.com/creativecommons/cccatalog-api/pull/453#discussion_r391738976), @makkoncept reasoned that it would be better to keep the docs the same.

#### Change `detail` parameter to be more readable.

I noticed that the `detail` parameter was a little difficult to interpret.
The new change should provide a clear description of the error for each `field` passed to the api.

## API Changes

The new API responses change accordingly:

```
GET /v1/images?q=+
```

```diff
 Vary: Accept

 {
-    "error_type": "InputError",
-    "detail": "Invalid input given for field ['q']. Hint: This field may not be blank.",
-    "field": [
+    "error": "InputError",
+    "detail": "Invalid input given for fields. 'q' -> This field may not be blank.",
+    "fields": [
         "q"
     ]
 }
```

---

```
GET /v1/images?q=+&page_size=ss
```

```diff
 Vary: Accept

 {
-    "error_type": "InputError",
-    "detail": "Invalid input given for field ['q', 'page_size']. Hint: This field may not be blank. A valid integer is required.",
-    "field": [
+    "error": "InputError",
+    "detail": "Invalid input given for fields. 'q' -> This field may not be blank. 'page_size' -> A valid integer is required.",
+    "fields": [
         "q",
         "page_size"
     ]
```
---

> #### Notes
>
> I was able to call the api after running `docker-compose up`.
>
> Requesting a review from @aldenstpage & @makkoncept.
>
> Thank you :smile: 

---

<details>

<summary>Developer Certificate of Origin</summary>

Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

</details>

### CODE REVIEW

**Comment by makkoncept** [comment]
@kelvindecosta my comment that you refer to in the PR description was only regarding the `fields` key. Anyways, I think @aldenstpage can look into this because the changes to the `details` were not discussed before. And also, there is already a PR open (#453) which addresses the same issues.

**Comment by kelvindecosta** [comment]
Yes, I am aware of the [open PR addressing the same issue](https://github.com/creativecommons/cccatalog-api/pull/453). I was hoping to add to the existing solution by working on the API, and then have it reviewed. I thought I was not violating the contribution guidelines as there was no activity in a week. Sorry for causing any confusion

**Comment by aldenstpage** [comment]
There seems to be something wrong with Travis, I'm force-merging this because the build has succeeded but they failed to give GitHub a callback.

**Comment by kelvindecosta** [comment]
@aldenstpage thank you for your feedback :smile:

**Pull request merged**
