### PR TITLE
Remove view count

### LINKED ISSUE #540: Phase out view_count column
We don't need the view_count column because the analytics API makes it obsolete. It should be removed from the schema through migrations, and the django cron job that updates it (as well as the accompanying over-engineered redis caching code) should be deleted.

### PR DESCRIPTION
**Pull request by ritesh-pandey**
## Fixes

Fixes #540 by @aldenstpage 

## Description

Removed view_count column of image table and its references in codebase.

## Technical details

view_count column in image table was used to perform analytics on image views. We used arcane mechanism to capture and analyse image view count. This is now deprecated.

Now that we have a dedicated mechanism of analytics, we no longer require this column and feature. A related cron job was also deleted.

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by aldenstpage** [comment]
It looks like there's a new build error, take a look at the Travis CI logs

**Comment by ritesh-pandey** [comment]
Ran the same on local. Worked fine.

The error says that it did not get response from 
`http://localhost:8000/v1/images?q=test` in stipulated time.

Can you help me as where to look for more information to fix this?

**Comment by aldenstpage** [comment]
If you expand the `load_sample_data.sh` logs, you can see that something has gone wrong:
```
INSERT 0 2

ERROR:  extra data after last expected column

CONTEXT:  COPY image, line 5001: "10494466,2018-09-11 13:06:48.062657+00,2018-10-19 14:20:07.92795+00,97f9ee0a-4f08-4027-85ca-a60e2f39..."

{"message": "Successfully scheduled task", "task_id": "dfcca007-548e-4627-b5f6-dcbb40cc3665", "status_check": "http://localhost:8001/task/dfcca007-548e-4627-b5f6-dcbb40cc3665"}{"message": "Successfully scheduled task", "task_id": "e8056bd5-b178-46a5-9d6e-73ae0b354925", "status_check": "http://localhost:8001/task/e8056bd5-b178-46a5-9d6e-73ae0b354925"}(integer) 1

$ bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8000/v1/images?q=test)" != "200" ]]; do sleep 5; done'
```

**Comment by ritesh-pandey** [comment]
`load_sample_data` was successful. But no output received by Travis. Build terminated.

**Comment by ritesh-pandey** [comment]
@aldenstpage Can you please suggest on how to proceed from here?

**Comment by aldenstpage** [comment]
Debugging Travis issues can be difficult; I hope it's a little easier now that we've switched to GitHub Actions (which will be a little more explicit about what step failed and run the tests much faster). Even with that change, end-to-end tests are difficult to work with because you often have to sift through a sea of application logs to find what went wrong.

Rather than figure out what's wrong with the build, I opted to start from scratch and open a new PR https://github.com/creativecommons/cccatalog-api/pull/597.

**Pull request closed without merging**
