### PR TITLE
[WIP] #209 Generates Polaroid Watermark

### PR DESCRIPTION
**Pull request by brenoferreira**
Includes the functions to generate the polaroid watermark with the attribution

### CODE REVIEW

**Comment by kgodey** [comment]
GitHub recently introduced draft pull requests for WIP pull requests: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by aldenstpage** [comment]
This looks good. I made a few minor changes to pass the style check and some [name shadowing issues](http://www.oznetnerd.com/python-shadowing/) (these did not cause any problems with your code, but can introduce hard-to-find bugs down the line).. The next step is going to be to design the endpoint and make this work with live images; I can take it from here if you'd like.

**Comment by aldenstpage** [comment]
I think this is ready to go. I did make a few minor adjustments, with the most significant one being a change to the `DejaVuSans-Bold.ttf` font (see [here](https://www.fontsquirrel.com/fonts/dejavu-sans)). This is the closest font available out of the box in the API's flavor of Linux. Is this alright or would you prefer another font?

**Comment by brenoferreira** [comment]
@aldenstpage this font is fine for me

**Pull request merged**
