### PR TITLE
Requirements version pinning

### PR DESCRIPTION
**Pull request by dhruvkb**
This PR addresses issue #223 by adding Pipenv to the development flow. This would allow us fine-grained control over our top-level dependencies. To ensure that the development dependencies such as `ipython` and `remote-pdb` do not get included in the production builds, these dependencies have been moved over to the `dev-packages` category.

### CODE REVIEW

**Comment by dhruvkb** [comment]
I'm stumped by the output given by Travis:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Can anyone help me out here?

**Comment by kgodey** [comment]
@dhruvkb you can rerun the Travis build in debug mode https://docs.travis-ci.com/user/running-build-in-debug-mode/ to SSH in and try running the failing command manually to see what's going on. You can also try running it locally to see if you're getting an error to see if the problem is just on Travis.

**Comment by dhruvkb** [comment]
Thanks @kgodey I'll look into it a bit more deeply.

**Comment by kgodey** [comment]
👍 for Pipenv, I updated one of my personal projects to use it recently and it's great.

**Comment by dhruvkb** [comment]
@aldenstpage Me too, virtualenvs are no fun. Are these deployment scripts tracked in this project? I could look into them if needed.
@kgodey I too learned of Pipenv just this year when I was looking for something like `npm` for Python.

**Comment by aldenstpage** [comment]
Sadly, our deployment scripts are not public at the moment. We are using a continuous deployment tool called Atlantis that can only be used in private repositories. In the near future, I plan to mirror the code so it's available to the community again.

Also, it's quite hard to test our infrastructure scripts without having administrative access to our servers, so I'm going to need to be the person to transition it to Pipenv anyway

**Comment by dhruvkb** [comment]
Resolved conflicts with the `master` branch which developed after the PR was opened.

**Comment by dhruvkb** [comment]
@aldenstpage while you are updating the deployment scripts, should I migrate the ingestion server to Pipenv too? If we're going with the upgrade, let's go all the way.

**Comment by aldenstpage** [comment]
@dhruvkb It would be great if you migrated Ingestion Server as well! That's run in a docker-container, so there will be no need for me to make any changes to the deployment scripts, and I'll be able to merge it as soon as the tests pass. If you're still interested in this task, I'd prefer it was done in a separate pull request.

**Comment by dhruvkb** [comment]
I was actually planning to do it! I was hesitating because this PR hadn't been merged so I didn't know if it was on the roadmap. I'll make a separate PR for the ingestion server as soon as possible. This one is for the Django container, does this need any work before merging?

**Comment by aldenstpage** [comment]
Nope, looks good! I'm going to alter the deployment scripts to make use of this. We'll be using `pipenv` from the next release and on.

**Pull request merged**
